language: node_js
node_js: "7.5"
cache: yarn

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
  - git config --global user.email "travis@travis-ci.org"		
  - git config --global user.name "Travis CI"

script:
  - ng test --browser ChromeHeadless --single-run
  - ng build --prod --aot --base-href "https://bgolyoo.github.io/chuck-norris-jokes-ui/"

after_success:
  - angular-cli-ghpages --no-silent

notifications:
  email:
    on_failure: never
    on_success: never
