language: node_js
node_js: "7.5"
cache: yarn

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - ng test --browser ChromeHeadless --single-run
  - ng build --prod --aot --base-href "https://bgolyoo.github.io/chuck-norris-jokes-ui/"

after_success:
  - angular-cli-ghpages

notifications:
  email:
    on_failure: never
    on_success: never
