language: node_js
node_js:
  - "7.5"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
  - npm install -g standard-version

script:
  - ng test --browser ChromeHeadless --single-run
  - ng build --prod --aot --base-href "https://bgolyoo.github.io/chuck-norris-jokes-ui/"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - standard-version --no-verify
  - git remote add origin https://${GH_TOKEN}@github.com/bgolyoo/chuck-norris-jokes-ui.git
  - git branch
  - git status
  - git push --follow-tags origin master

after_success:
  - angular-cli-ghpages

notifications:
  email:
    on_failure: change
    on_success: change
